#!/usr/bin/env bash

# careful, I use gnu everything on my mac
# see https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/

CACHE_DIR=${ACH_CACHE_DIR:-$HOME/.cache/ach}
[ ! -d $CACHE_DIR ] && mkdir -p $CACHE_DIR
LOCK=${ACH_LOCK_FILE:-$CACHE_DIR/lock}
CONTENTS=""

check_expiration() {
    if [ -f $file ]; then
        CONTENTS="$(credout $file)"
        local expiration=$(date -d "$(echo $CONTENTS | jq -r '.Expiration' | sed 's/T/ /')" +%s)
        local now=$(date +%s)

        echo "check expiration, file: $file, expiration: $expiration, now: $now" >&2

        if (( expiration < now )); then
            echo "file too old, removing file $file" >&2
            CONTENTS=""
            rm $file
        fi
    fi
}

check_file_age() {
    local timeout=$1
    local file=$2

    if [ -f $file ]; then
        local age=$(stat --format='%Y' $file)
        local now=$(date +%s)

        echo "check file age, file: $file (age: $age), timeout: $timeout, now: $now" >&2

        if (( age < (now - $timeout) )); then
            echo "file too old, removing file $file" >&2
            rm $file
        fi
    fi
}

cacheget() {
    local file=$1
    local expiry_function=$2
    shift 2

    eval "$expiry_function $file"

    if [ ! -f $file ]; then
        echo "cache miss, generating $file" >&2
        eval "$@ > $file"
    else
        echo "cache hit, retrieving $file" >&2
    fi
}

refreshaccounts() {
    echo alks developer accounts -e >&2
    alks developer accounts -e | awk '$2~/^[^-]*$/'
}

refreshcreds() {
    local account_list=$CACHE_DIR/accounts
    cacheget $account_list "check_file_age $((60 * 60 * 24))" refreshaccounts
    source $account_list

    alks_account=${ACCOUNT}_admin
    if [ ! -v $alks_account ]; then
        alks_account=${ACCOUNT}_labadmin
    fi
    if [ ! -v $alks_account ]; then
        alks_account=${ACCOUNT}_security
    fi
    echo $alks_account >&2
    echo alks session open -a -a ${!alks_account} -o aws >&2

    local creds=$(alks sessions open -i -a "${!alks_account}" -o aws)
    echo $creds | gpg --encrypt --armor -r $ACH_GPG_RECIPIENT
}

credout() {
    if [ -z "$CONTENTS" ]; then
        CONTENTS=$(cat $1 | gpg --decrypt)
    fi

    if [ -t 1 ]; then
        echo $CONTENTS | jq -r
    else
        echo $CONTENTS
    fi
}

main() {
    [ -z $ACCOUNT ] && {
        echo error not account selected
        exit 1
    }
    local credfile=$CACHE_DIR/$ACCOUNT.json.enc
    cacheget $credfile check_expiration refreshcreds
    credout $credfile
}

ACCOUNT=${1:-$AWS_PROFILE}
(
    flock -x -w 30 200 || {
        echo "Failed to obtain lock" >&2
        exit 1
    }
    date 2>> $CACHE_DIR/log 1>&2
    main 2>> $CACHE_DIR/log
) 200>$LOCK
